####### cob_offset #######
float32 cob_x_offset_m
float32 cob_y_offset_m

####### FeedForward #####
float32 hip_roll_swap_angle_rad

########## Gain ########
#by gyro
float32 gyro_gain

#by imu
float32 foot_roll_angle_gain
float32 foot_pitch_angle_gain

#by ft sensor
float32 foot_x_force_gain
float32 foot_y_force_gain
float32 foot_z_force_gain
float32 foot_roll_torque_gain
float32 foot_pitch_torque_gain

########## TIME CONSTANT ##########
#by gyro

#by imu
float32 foot_roll_angle_time_constant
float32 foot_pitch_angle_time_constant

#by ft
float32 foot_x_force_time_constant
float32 foot_y_force_time_constant
float32 foot_z_force_time_constant
float32 foot_roll_torque_time_constant
float32 foot_pitch_torque_time_constant